cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('accounts/',include('allauth.urls'))

]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

shop/urls.py
from . import views
from django.urls import path

app_name='shop'
urlpatterns=[
    path('',views.index,name='index'),
    path('checkout/',views.checkout,name='checkout'),
    path('product/<int:id>/',views.product,name='product'),
    path('store/',views.store,name='store'),
    path('to_bank/<int:order_id>/',views.to_bank,name='to_bank'),
    path('callback/',views.callback,name='callback'),
    path('profile/',views.profile,name='profile'),
    path('orders/',views.orders,name='orders'),
    path('searched_products/',views.search,name='search'),
    path('order_detail/<int:order_id>/',views.order_detail,name='order_detail')
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Product(models.Model):
    name= models.CharField(max_length=100)
    description= models.TextField(max_length=3000)
    create_time= models.DateTimeField(auto_now_add=True)
    update_time= models.DateTimeField(auto_now=True)
    image=models.ImageField(upload_to='image/product/%Y/%m/%d')
    price=models.DecimalField(max_digits=10, decimal_places=0)
    inventory= models.IntegerField(null=False)

    class Meta:
        ordering=('create_time',)
        verbose_name_plural='products'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product', args=[self.id])

class Order(models.Model):
    customer=models.ForeignKey(User,on_delete=models.CASCADE)
    order_date=models.DateTimeField(auto_now_add=True)
    payed=models.BooleanField(default=False)
    address=models.ForeignKey('Address',on_delete=models.SET_NULL,null=True)
    def __str__(self):
        return f'{self.address}, {self.orderitem}'
    class Meta:
        ordering=('order_date',)
        verbose_name_plural='Orders'

class Address(models.Model):
    name=models.CharField(max_length=20)
    mobile=models.CharField(max_length=11)
    address=models.CharField(max_length=50)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return f'{self.address} , {self.name} , {self.mobile} , {self.user}'
    class Meta:
        verbose_name_plural='Addresses'

class OrderItem(models.Model):
    order=models.ForeignKey(Order, related_name='orderitem', on_delete=models.CASCADE)
    product= models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    product_price = models.DecimalField(max_digits=10, decimal_places=0)
    product_count= models.PositiveIntegerField()
    product_cost = models.DecimalField(max_digits=10, decimal_places=0)

    def __str__(self):
        return str(self.id)
    class Meta:
        verbose_name_plural='OrderItems'

class Invoice(models.Model):
    order=models.ForeignKey(Order,on_delete=models.SET_NULL,null=True)
    order_items=models.CharField(max_length=400,)
    invoice_date=models.DateTimeField(auto_now_add=True)
    authority=models.CharField(max_length=200,blank=True,null=True) #maleke invoice= esme moshtari
    def __str__(self):
        return str(self.id)
    class Meta:
        verbose_name_plural='Invoices'


class Transaction(models.Model):
    STATUS_CHOICES=(
        ('pending','Pending'),
        ('failed','Failed'),
        ('completed','Completed'),
    )
    invoice=models.ForeignKey(Invoice, on_delete=models.SET_NULL, null=True)
    transaction_date=models.DateTimeField(auto_now_add=True)
    amount=models.DecimalField(max_digits=10, decimal_places=0)
    status=models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')
    def __str__(self):
        return str(self.id)
    class Meta:
        verbose_name_plural='Transactions'

shop/forms.py
from django import forms
from .models import Address

class AddressForm(forms.ModelForm):
    class Meta:
        model=Address
        fields=['name', 'mobile', 'address']

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from cart.forms import CartAddProductForm
from django.contrib.auth.decorators import login_required
from .forms import AddressForm
from . import models
from cart.cart import Cart
from django.db.models import Q
from decimal import Decimal
from zeep import Client
from django.http import HttpResponse
 
def index(request):
    product_list = models.Product.objects.order_by('-create_time')[:10]
    return render(request, 'index.html', {'product_list': product_list})


def product(request, id):
    product_detail = get_object_or_404(models.Product, id=id)
    cart_add_product_form = CartAddProductForm()
    return render(request, 'product.html',
                  {'product_detail': product_detail, 'cart_add_product_form': cart_add_product_form})


def store(request):
    products = models.Product.objects.order_by('-create_time')
    return render(request, 'store.html', {'products': products})


def search(request):
    query = request.GET.get('q')
    queryset_list = []
    if query:
        queryset_list = models.Product.objects.filter(Q(name__icontains=query)).distinct()
    elif query == '':
        queryset_list = models.Product.objects.all()
    products = queryset_list
    return render(request, 'searched_products.html', {'products': products})
  

@login_required()
def checkout(request):
    cart = Cart(request)
    if not cart:
        return redirect('shop:store')
    if request.method != 'POST':
        form = AddressForm()
    else:
        form = AddressForm(request.POST)
        if form.is_valid():
            address = models.Address.objects.create(
                name=request.POST.get('name'),
                mobile=request.POST.get('mobile'),
                address=request.POST.get('address'),
                user=request.user
            )

            order = models.Order.objects.create(customer=request.user, address=address)
            for item in cart:
                models.OrderItem.objects.create(
                    order=order, 
                    product=item['product'],
                    product_price=item['price'],
                    product_count=item['product_count'],
                    product_cost=Decimal(item['product_count']) * Decimal(item['price'])
                )
        cart.clear()
        return redirect('shop:order_detail', order.id)
    return render(request, 'checkout.html', {'form': form})


def profile(request):
    return render(request, 'profile.html')


def orders(request):
    orders = models.Order.objects.order_by('-order_date')
    return render(request, 'orders.html', {'orders': orders})


def order_detail(request, order_id):
    order = get_object_or_404(models.Order, id=order_id)
    return render(request, 'order_detail.html', {'order': order})

MERCHANT='*******************'
client=Client('https://www.zarinpal.com/pg/services/WebGate/wsdl')
def to_bank(request,order_id):
    order=get_object_or_404(models.Order,id=order_id)
    amount=0
    order_items=models.OrderItem.objects.filter(order=order)
    for item in order_items:
        amount+=item.product_price
    callbackUrl='http://beontop.ir/callback/'
    mobile=''
    email=''
    description='Test'
    result=client.service.PaymentRequest(MERCHANT,amount,description,email,mobile,callbackUrl)
    if result.Status == 100 and len(result.Authority) == 36:
        x=[]
        for item in order_items:
            x.append(item)
        models.Invoice.objects.create(order=order,
                                      order_items=x,
                                      authority=result.Authority)
        return redirect('https://www.zarinpal.com/pg/StartPay/'+result.Authority)
    else:
        return HttpResponse('Error code' + str(result.Status))


def callback(request):
    if request.GET.get('Status')=='OK':
        authority=request.GET.get('Authority')
        invoice=get_object_or_404(models.Invoice,authority=authority)
        amount=0
        order=invoice.order
        order_items=models.OrderItem.objects.filter(order=order)
        for item in order_items:
            amount+=item.product_cost
        result=client.service.PaymentVerification(MERCHANT,authority,amount)
        if result.Status == 100:
            
            order.payed=True
            order.save()
            return render(request,'callback.html',{'invoice':invoice})
        else:
            return HttpResponse('error'+str(result.Status))
    else:
        return HttpResponse('error')

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock title %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

  </head>
  <body>

  <div class="site-wrap">
       <header class="site-navbar" role="banner">
      <div class="site-navbar-top">
        <div class="container">
          <div class="row align-items-center">

            <div class="col-6 col-md-4 order-2 order-md-1 site-search-icon text-left">
                <form action="{% url 'shop:search' %}"method="get"class="site-block-top-search">
                    <span class="icon icon-search"></span>
                    <input placeholder="Search" type="text"class="form-control border-0" name="q"value="{{ request.GET.q }}">
                </form>
            </div>

            <div class="col-12 mb-3 mb-md-0 col-md-4 order-1 order-md-2 text-center">
              <div class="site-logo">
                <a href="{% url 'shop:index' %}" class="js-logo-clone">Ecommerce</a>
              </div>
            </div>

            <div class="col-6 col-md-4 order-3 order-md-3 text-right">
              <div class="site-top-icons">
                <ul>
                    {% if user.is_authenticated %}
                  <li><a href="{% url 'account_logout' %}"><span ></span>Logout</a></li>
                  <li><a href="{% url 'shop:profile' %}"><span></span>Profile</a></li>
                    {% else %}
                     <li><a href="{% url 'account_login' %}"><span ></span>Login</a></li>
                  <li><a href="{% url 'account_signup' %}"><span></span>Signup</a></li>
                      {% endif %}
                  <li>

                    <a href="{% url 'cart:cart_detail' %}" class="site-cart">
                      <span class="icon icon-shopping_cart"></span>
                      <span class="count">{{cart.cart_item_count}}</span>
                    </a>
                  </li>
                  <li class="d-inline-block d-md-none ml-md-0"><a href="#" class="site-menu-toggle js-menu-toggle"><span class="icon-menu"></span></a></li>
                </ul>
              </div>
            </div>

          </div>
        </div>
      </div>
      <nav class="site-navigation text-right text-md-center" role="navigation">
        <div class="container">
          <ul class="site-menu js-clone-nav d-none d-md-block">
            <li>
              <a href="{% url 'shop:index' %}">Home</a>
            </li>

            <li><a href="{% url 'shop:store' %}">Store</a></li>

          </ul>
        </div>
      </nav>
    </header>
      {% block content %}{% endblock content %}
      </div>

  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>

  <script src="{% static 'js/main.js' %}"></script>

  </body>
</html>

shop/templates/callback.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Callback{% endblock title %}
{% block content %}
    <h1 class="text-center"> Payment Detail</h1>
    <div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12 order-detail">
                <div class="section-title text-center">
                    <h3 class="title">Thank You</h3>

                </div>
                <div class="order-summary">
                    <p>Your Invoice Number : {{ invoice.id }}</p>
                </div>
            </div>
        </div>
    </div>

    </div>
{% endblock content %}

shop/templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Checkout{% endblock title %}
{% block content %}




    <div class="site-section">
      <div class="container">

        <div class="row">
          <div class="col-md-6 mb-5 mb-md-0">
            <h2 class="h3 mb-3 text-black">Adress</h2>
            <div class="p-3 p-lg-5 border">
              <div class="form-group ">
                  <form action="{% url 'shop:checkout' %}"method="post">
                      {% csrf_token %}
                      {{ form.as_p }}
                      <button type="submit"class="btn btn-primary btn-lg py-3 btn-block">Place Order</button>
                  </form>
              </div>




            </div>
          </div>
          <div class="col-md-6">
            <div class="row mb-5">
              <div class="col-md-12">
                <h2 class="h3 mb-3 text-black">Your Order</h2>
                <div class="p-3 p-lg-5 border">
                  <table class="table site-block-order-table mb-5">
                    <thead>
                    <tr>
                      <th>Product</th>
                      <th>Total</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in cart %}

                      <tr>
                        <td>{{item.product_count}} X {{ item.product.name }}</td>
                        <td>${{item.total_price}}</td>
                      </tr>
                      {% endfor %}
                      <tr>
                        <td class="text-black font-weight-bold"><strong>Order Total</strong></td>
                        <td class="text-black font-weight-bold"><strong>${{cart.get_total_price}}</strong></td>
                      </tr>
                    </tbody>
                  </table>


                </div>
              </div>
            </div>

          </div>
        </div>

      </div>
    </div>





{% endblock content %}

shop/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Detail{% endblock title %}
{% block content %}




 <div class="site-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-12">
            <div class="site-blocks-table">
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th class="product-thumbnail">Image</th>
                    <th class="product-name">Product</th>
                    <th class="product-price">Price</th>
                    <th class="product-quantity">Quantity</th>
                    <th class="product-total">Total</th>
                    <th class="product-remove">Remove</th>
                  </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                {% with product=item.product %}
                  <tr>
                    <td class="product-thumbnail">
                        <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" alt="Image" class="img-fluid"></a>
                    </td>
                    <td class="product-name">
                      <h2 class="h5 text-black">{{ product.name }}</h2>
                    </td>
                    <td>${{item.price}}</td>
                    <td>
                        <form action="{% url 'cart:cart_add' product.id %}" method="post">
                            {{ item.update_product_count_form.product_count }}
                            {{ item.update_product_count_form.update }}
                            {% csrf_token %}
                            <input type="submit" value="Update">
                        </form>

                    </td>
                    <td>${{item.total_price}}</td>
                    <td><a href="{% url 'cart:cart_remove' product.id %}" class="btn btn-primary btn-sm">X</a></td>
                  </tr>
{% endwith %}
{% endfor %}

                </tbody>
              </table>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="row mb-5">
              <div class="col-md-6">
                  <a href="{% url 'shop:store' %}"><button class="btn btn-outline-primary btn-sm btn-block">Continue Shopping</button>
              </a></div>
            </div>
          </div>
          <div class="col-md-6 pl-5">
            <div class="row justify-content-end">
              <div class="col-md-7">
                <div class="row">
                  <div class="col-md-12 text-right border-bottom mb-5">
                    <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                  </div>
                </div>
                <div class="row mb-3">
                  <div class="col-md-6">
                    <span class="text-black">Total</span>
                  </div>
                  <div class="col-md-6 text-right">
                    <strong class="text-black">${{cart.get_total_price}}</strong>
                  </div>
                </div>


                <div class="row">
                  <div class="col-md-12">
                      <a href="{% url 'shop:checkout' %}"><button class="btn btn-primary btn-lg py-3 btn-block" >Checkout</button>
                 </a> </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>






{% endblock content %}

shop/templates/form.html
{% load forms_tags widget_tweaks %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
    {% endfor %}
  </div>
{% endif %}

{% for field in form %}
  <div class="form-group text-center">
    {{ field.label_tag }}
    {% render_field field class=field|input_class %}
    {% for error in field.errors %}
      <div class="invalid-feedback">
        {{ error }}
      </div>
    {% endfor %}
    {% if field.help_text %}
      <small class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
{% endfor %}

shop/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block content %}
 <div class="site-section site-section-sm site-blocks-1">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="">
            <div class="icon mr-4 align-self-start">
              <span class="icon-truck"></span>
            </div>
            <div class="text">
              <h2 class="text-uppercase">Free Shipping</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="100">
            <div class="icon mr-4 align-self-start">
              <span class="icon-refresh2"></span>
            </div>
            <div class="text">
              <h2 class="text-uppercase">Free Returns</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="200">
            <div class="icon mr-4 align-self-start">
              <span class="icon-help"></span>
            </div>
            <div class="text">
              <h2 class="text-uppercase">Customer Support</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="site-section site-blocks-2">
      <div class="container">
        <div class="row">
          <div class="col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0" data-aos="fade" data-aos-delay="">
            <a class="block-2-item" href="#">
              <figure class="image">
                <img src="{% static 'images/women.jpg' %}" alt="" class="img-fluid">
              </figure>
              <div class="text">
                <span class="text-uppercase">Collections</span>
                <h3>Women</h3>
              </div>
            </a>
          </div>
          <div class="col-sm-6 col-md-6 col-lg-4 mb-5 mb-lg-0" data-aos="fade" data-aos-delay="100">
            <a class="block-2-item" href="#">
              <figure class="image">
                <img src="{% static 'images/children.jpg' %}" alt="" class="img-fluid">
              </figure>
              <div class="text">
                <span class="text-uppercase">Collections</span>
                <h3>Children</h3>
              </div>
            </a>
          </div>
          <div class="col-sm-6 col-md-6 col-lg-4 mb-5 mb-lg-0" data-aos="fade" data-aos-delay="200">
            <a class="block-2-item" href="#">
              <figure class="image">
                <img src="{% static 'images/men.jpg' %}" alt="" class="img-fluid">
              </figure>
              <div class="text">
                <span class="text-uppercase">Collections</span>
                <h3>Men</h3>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>






    <div class="site-section block-3 site-blocks-2 bg-light">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-7 site-section-heading text-center pt-4">
            <h2>Featured Products</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="nonloop-block-3 owl-carousel">
                {% for product in product_list %}
              <div class="item">
                <div class="block-4 text-center">
                    <a href="{{product.get_absolute_url}}">
                  <figure class="block-4-image">
                    <img src="{{ product.image.url }}" alt="Image placeholder" class="img-fluid">
                  </figure>
                    </a>
                  <div class="block-4-text p-4">
                    <h3><a href="{{product.get_absolute_url}}">{{ product.name }}</a></h3>

                    <p class="text-primary font-weight-bold">${{product.price}}</p>
                  </div>
                </div>
              </div>
                {% endfor %}

            </div>
          </div>
        </div>
      </div>
    </div>






{% endblock content %}

shop/templates/order_detail.html
{% extends 'base.html' %}
{% block title %}
    Order Detail
{% endblock title %}
{% block content %}
        <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            <span class="icon-check_circle display-3 text-success"></span>
            <h2 class="display-3 text-black">Thank you!</h2>
            <p class="lead mb-5">You order was successfuly completed.</p>
            <p class="lead mb-5">Your Order Number : {{ order.id }}</p>
            <p><a href="{% url 'shop:to_bank' order.id %}" class="btn btn-primary">Online Payment</a></p>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

shop/templates/orders.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Orders{% endblock title %}
{% block content %}
    <h1 class="text-center">Your Orders</h1>
        <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card">
           <div class="card-body">
    {% for order in orders %}
    {% if order.payed %}
    <p class="row btn btn-success">Paid : {{ order.payed }}</p>
    <p>Order id :{{ order.id }}</p>
    <p class="btn">Address :{{ order.address.name }} , {{ order.address.mobile }}</p>
               <hr>
    {% else %}
                <p class="row btn btn-danger">Paid : {{ order.payed }}</p>
    <p>Order id :{{ order.id }}</p>
    <p class="btn">Address : {{ order.address.address }}, {{ order.address.name }} , {{ order.address.mobile }}</p>
    <hr>
               {% endif %}
           {% empty %}
           <p class="btn btn-primary">No Orders Yet</p>
           {% endfor %}
           </div>
           </div>
           </div>
           </div>
{% endblock content %}

shop/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Product{% endblock title %}
{% block content %}



<div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <img src="{{product_detail.image.url}}" alt="Image" class="img-fluid">
          </div>
          <div class="col-md-6">
            <h2 class="text-black">{{product_detail.name}}</h2>
            <p>{{ product_detail.description }}</p>
              <p><strong class="text-primary h4">${{product_detail.price}}</strong></p>
            <div class="mb-5">
              <div class="input-group mb-3" style="max-width: 120px;">
              <div class="input-group-prepend">
                  <form action="{% url 'cart:cart_add' product_detail.id %}" method="post">
                      {% csrf_token %}
                      {{ cart_add_product_form }}
                      <hr>
                      <input type="submit"class="btn btn-block btn-primary" value="Add To Cart">
                  </form>

          </div>
        </div>
      </div>
    </div>
    </div>
    </div>
    </div>



{% endblock content %}

shop/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Profile{% endblock title %}
{% block content %}

    <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card">
           <div class="card-body">

               <div class="text-center">

                   <a class="btn btn-success" href="{% url 'account_email' %}">Add Email</a><br><br>
                   <a class="btn btn-success" href="{% url 'account_change_password' %}">Password Change</a><br><br>
                   <a class="btn btn-success" href="{% url 'account_reset_password' %}">Password Reset</a><br><br>
                   <a class="btn btn-success" href="{% url 'shop:orders' %}">Your Orders</a>
               </div>
            </div>
        </div>


    </div>


    </div>



{% endblock content %}

shop/templates/searched_products.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Searched Products{% endblock title %}
{% block content %}



<div class="site-section">
      <div class="container">
        <div class="row mb-5">
            <div class="row mb-5">
{%  for product in products %}
              <div class="col-sm-6 col-lg-4 mb-4" data-aos="fade-up">
                <div class="block-4 text-center border">
                  <figure class="block-4-image">
                    <a href="{{product.get_absolute_url}}"><img src="{{product.image.url}}" alt="Image placeholder" class="img-fluid"></a>
                  </figure>
                  <div class="block-4-text p-4">
                    <h3><a href="{{product.get_absolute_url}}">{{product.name}}</a></h3>

                    <p class="text-primary font-weight-bold">${{product.price}}</p>
                  </div>
                </div>
              </div>
                {% endfor %}
            </div>
          </div>
      </div>
    </div>



{% endblock content %}

shop/templates/store.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Store{% endblock title %}
{% block content %}



<div class="site-section">
      <div class="container">
        <div class="row mb-5">
            <div class="row mb-5">
{%  for product in products %}
              <div class="col-sm-6 col-lg-4 mb-4" data-aos="fade-up">
                <div class="block-4 text-center border">
                  <figure class="block-4-image">
                    <a href="{{product.get_absolute_url}}"><img src="{{product.image.url}}" alt="Image placeholder" class="img-fluid"></a>
                  </figure>
                  <div class="block-4-text p-4">
                    <h3><a href="{{product.get_absolute_url}}">{{product.name}}</a></h3>

                    <p class="text-primary font-weight-bold">${{product.price}}</p>
                  </div>
                </div>
              </div>
                {% endfor %}
            </div>
          </div>
      </div>
    </div>



{% endblock content %}